---
title: "CAUTI"
author: "Prashant Kumar"
format: docx
editor: source
---

```{r message=FALSE, warning=FALSE}
library(readxl)
library(tidyverse)
library(lubridate)
library(survival)
library(survminer)
```

```{r echo=FALSE}
cauti <- read_excel("E:/dataset/Cauti Study data 4-2024.xlsx")
```

```{r}
infection <- cauti %>% 
  filter(CAUTI_LDA == "Y") %>% 
  select(PAT_MRN_ID, HOSP_ADMSN_TIME, HOSP_DISCH_TIME, CAUTI_Infection_date, ConsecutiveFoley, PLACEMENT_DATE, REMOVAL_DATE, CAUTI_LDA, ConsecutiveFoley)
id <- infection %>%
  distinct(PAT_MRN_ID) %>%
  mutate(ID = row_number())
infection <- infection %>%
  left_join(id, by = "PAT_MRN_ID") %>% 
  select(ID, everything())

infection <- infection %>% 
  mutate(
    REMOVAL_DATE = ifelse(REMOVAL_DATE > HOSP_DISCH_TIME, 
                          HOSP_DISCH_TIME, 
                          REMOVAL_DATE)) %>% 
  mutate(
    PLACEMENT_DATE = ifelse(PLACEMENT_DATE < HOSP_ADMSN_TIME,
                            HOSP_ADMSN_TIME, PLACEMENT_DATE))%>%
  mutate(
    REMOVAL_DATE = as.POSIXct(REMOVAL_DATE, format = "%m/%d/%Y %H:%M"),
    PLACEMENT_DATE = as.POSIXct(PLACEMENT_DATE, format = "%m/%d/%Y %H:%M"),
    HOSP_ADMSN_TIME = as.POSIXct(HOSP_ADMSN_TIME, format = "%m/%d/%Y %H:%M"),
    HOSP_DISCH_TIME = as.POSIXct(HOSP_DISCH_TIME, format = "%m/%d/%Y %H:%M")
  ) 

invalid_placement_dates1 <- infection %>%
   mutate(
    REMOVAL_DATE = as.POSIXct(REMOVAL_DATE, format = "%m/%d/%Y %H:%M"),
    PLACEMENT_DATE = as.POSIXct(PLACEMENT_DATE, format = "%m/%d/%Y %H:%M"),
    HOSP_ADMSN_TIME = as.POSIXct(HOSP_ADMSN_TIME, format = "%m/%d/%Y %H:%M"),
    HOSP_DISCH_TIME = as.POSIXct(HOSP_DISCH_TIME, format = "%m/%d/%Y %H:%M")
  ) %>% 
  filter(PLACEMENT_DATE < HOSP_ADMSN_TIME | PLACEMENT_DATE > HOSP_DISCH_TIME)

foley_day <- infection %>% 
  mutate(CAUTI_LDA2 = ifelse(ConsecutiveFoley == "N", "0", CAUTI_LDA)) %>% 
  mutate(
    foleyday = round(as.numeric(
     difftime(REMOVAL_DATE, PLACEMENT_DATE, units = "days")) + 1
  )) %>% 
  arrange(ID, HOSP_ADMSN_TIME) %>%
  group_by(ID, HOSP_ADMSN_TIME) %>%
  mutate(num_foleys = cumsum(!duplicated(PLACEMENT_DATE))) %>% 
  mutate(r_date = lag(REMOVAL_DATE),
         foley_gap = ifelse(
           row_number() == 1, 0,
           as.numeric(difftime(
             PLACEMENT_DATE, 
             r_date, units = "days")))) %>% 
  mutate(consec_foley = cumsum(ifelse(
    row_number() == 1, 1, 
    ifelse(foley_gap > 1, 1, 0)))) %>% 
   mutate(consec_foley = ifelse(CAUTI_LDA2 == 1, 0, consec_foley)) %>% 
  mutate(foley_gap = round(foley_gap)) %>% 
  ungroup()




```

```{r}
no_infection <- cauti %>% 
  filter(CAUTI_LDA == "N") %>% 
  select(PAT_MRN_ID, HOSP_ADMSN_TIME, HOSP_DISCH_TIME, PLACEMENT_DATE, REMOVAL_DATE, CAUTI_LDA, PAT_MRN_ID, ConsecutiveFoley)
id1 <- no_infection %>%
  distinct(PAT_MRN_ID) %>%
  mutate(ID = row_number())
no_infection <- no_infection %>%
  left_join(id1, by = "PAT_MRN_ID") %>% 
  select(ID, PAT_MRN_ID, everything())

no_infection <- no_infection %>% 
  mutate(
    REMOVAL_DATE = ifelse(REMOVAL_DATE > HOSP_DISCH_TIME | REMOVAL_DATE < PLACEMENT_DATE, 
                          HOSP_DISCH_TIME, 
                          REMOVAL_DATE), 
    PLACEMENT_DATE = ifelse(PLACEMENT_DATE < HOSP_ADMSN_TIME | PLACEMENT_DATE > HOSP_DISCH_TIME,
                            HOSP_ADMSN_TIME, PLACEMENT_DATE)
    ) %>% 
    mutate(
    REMOVAL_DATE = as.POSIXct(REMOVAL_DATE, format = "%m/%d/%Y %H:%M"),
    PLACEMENT_DATE = as.POSIXct(PLACEMENT_DATE, format = "%m/%d/%Y %H:%M"),
    HOSP_ADMSN_TIME = as.POSIXct(HOSP_ADMSN_TIME, format = "%m/%d/%Y %H:%M"),
    HOSP_DISCH_TIME = as.POSIXct(HOSP_DISCH_TIME, format = "%m/%d/%Y %H:%M")
  )

invalid_placement_dates2 <- no_infection %>%
   mutate(
    REMOVAL_DATE = as.POSIXct(REMOVAL_DATE, format = "%m/%d/%Y %H:%M"),
    PLACEMENT_DATE = as.POSIXct(PLACEMENT_DATE, format = "%m/%d/%Y %H:%M"),
    HOSP_ADMSN_TIME = as.POSIXct(HOSP_ADMSN_TIME, format = "%m/%d/%Y %H:%M"),
    HOSP_DISCH_TIME = as.POSIXct(HOSP_DISCH_TIME, format = "%m/%d/%Y %H:%M")
  ) %>% 
  filter(PLACEMENT_DATE < HOSP_ADMSN_TIME | PLACEMENT_DATE > HOSP_DISCH_TIME)




```







```{r}
id <- cauti %>%
  distinct(PAT_MRN_ID) %>%
  mutate(ID = row_number())
new_cauti <- cauti %>%
  left_join(id, by = "PAT_MRN_ID") %>% 
  select(-"PAT_MRN_ID") %>% 
  select(ID, everything())
```


```{r}
new_cauti1 <- new_cauti %>% 
  filter(!PAT_AGE <= 17) %>% 
  filter(Gender!= "Unknown", !is.na(ID)) %>% 
  mutate(
   Gender = if_else(Gender == "Male", 0, 1),
   DIABETES_ON_PROBLEM_LIST = if_else(
     DIABETES_ON_PROBLEM_LIST == "Y", 1, 0),
   RENAL_INSUFFICIENY_ON_PROBLEM_LIST = if_else(
     RENAL_INSUFFICIENY_ON_PROBLEM_LIST == "Y", 1, 0),
   Bowel_Incontinence = if_else(
     Bowel_Incontinence == "Y", 1, 0),
   Urinary_Incontinence = if_else(
     Urinary_Incontinence == "Y", 1, 0),
   ORDER_FOR_FOLEY = if_else(
     ORDER_FOR_FOLEY == "Y", 1, 0),
   CAUTI_LDA = if_else(
     CAUTI_LDA == "Y", 1, 0),
   CAUTI_Date = as.Date(CAUTI_Infection_date, format = "%m/%d/%Y"),
   admissionday = round(as.numeric(
     difftime(HOSP_DISCH_TIME, HOSP_ADMSN_TIME, units = "days")) + 1),
   CHG = (CHG_NUMERATOR / CHG_DENOMINATOR) * 100,
   chg_100 = ifelse(CHG >= 100, 100, CHG),
   meatal = (Meatal_Numerator/Meatal_Denominator)* 100,
   meatal_100 = ifelse(meatal >= 100, 100, meatal)) %>%
  mutate(
    BMI_30 = ifelse(PAT_BMI < 30, 0, 1),
    BMI_cat = cut(PAT_BMI, breaks = c(-Inf, 18.5, 25, 30, Inf), 
                  labels = c('underweight', 
                             'healthy weight', 
                             'overweight', 
                             'obese'))) %>% 
  mutate(
    Age_50 = ifelse(PAT_AGE < 50, 0, 1),
    Age_Cat = cut(PAT_AGE, breaks = c(-Inf, 50, 60, 70, 80, Inf), 
                  labels = c('<50', 
                             '50-59', 
                             '60-69', 
                             '70-79', 
                             '>=80'))) %>% 
  mutate(
    CHG_Cat = cut(CHG, breaks = c(0, 49, 79, 100), 
                  labels = c('0-49', '50-79', '80-100'))) %>% 
  mutate(
    Meatal_Cat = cut(meatal, breaks = c(0, 49, 79, 100), 
                     labels = c('0-49', '50-79', '80-100'))) 

new_cauti1 <- new_cauti1 %>% 
   mutate(
    REMOVAL_DATE = ifelse(
      REMOVAL_DATE > HOSP_DISCH_TIME | REMOVAL_DATE < PLACEMENT_DATE, 
                          HOSP_DISCH_TIME, 
                          REMOVAL_DATE), 
    PLACEMENT_DATE = ifelse(
      PLACEMENT_DATE < HOSP_ADMSN_TIME | PLACEMENT_DATE > HOSP_DISCH_TIME,
                            HOSP_ADMSN_TIME, PLACEMENT_DATE)
    ) %>% 
    mutate(
    REMOVAL_DATE = as.POSIXct(REMOVAL_DATE, format = "%m/%d/%Y %H:%M"),
    PLACEMENT_DATE = as.POSIXct(PLACEMENT_DATE, format = "%m/%d/%Y %H:%M"),
    HOSP_ADMSN_TIME = as.POSIXct(HOSP_ADMSN_TIME, format = "%m/%d/%Y %H:%M"),
    HOSP_DISCH_TIME = as.POSIXct(HOSP_DISCH_TIME, format = "%m/%d/%Y %H:%M")
  )


new_cauti2 <- new_cauti1 %>% 
  mutate(CAUTI_LDA2 = ifelse(ConsecutiveFoley == "N", "0", CAUTI_LDA)) %>% 
  mutate(
    foleyday = round(as.numeric(
     difftime(REMOVAL_DATE, PLACEMENT_DATE, units = "days")) + 1
  )) %>% 
  arrange(ID, HOSP_ADMSN_TIME) %>%
  group_by(ID, HOSP_ADMSN_TIME) %>%
  mutate(num_foleys = cumsum(!duplicated(PLACEMENT_DATE))) %>% 
  mutate(r_date = lag(REMOVAL_DATE),
         foley_gap = ifelse(
           row_number() == 1, 0,
           as.numeric(difftime(
             PLACEMENT_DATE, 
             r_date, units = "days")))) %>% 
  mutate(consec_foley = cumsum(ifelse(
    row_number() == 1, 1, 
    ifelse(foley_gap > 1, 1, 0)))) %>% 
   mutate(consec_foley = ifelse(CAUTI_LDA2 == 1, 0, consec_foley)) %>% 
  mutate(foley_gap = round(foley_gap)) %>% 
  ungroup()

new_cauti2$r_date
```


```{r}
cauti_freq <- new %>%
  count(CAUTI_LDA) %>%
  mutate(percentage = n / sum(n) * 100) %>%
  arrange(desc(n))

```

```{r}
cauti_new <- new %>% 
  group_by(ID, HOSP_ADMSN_TIME, PLACEMENT_DATE) %>%
  mutate(
    ConsecutiveFoley = ifelse(ConsecutiveFoley == "N", 0, 1)
  ) %>%
  ungroup()
```


```{r}
model <- glm(
  CAUTI_LDA ~ PAT_AGE + Gender + PAT_BMI + DIABETES_ON_PROBLEM_LIST + RENAL_INSUFFICIENY_ON_PROBLEM_LIST + 
    Bowel_Incontinence + Urinary_Incontinence + CHG_Cat + Meatal_Cat + ORDER_FOR_FOLEY,
  data = cauti_new,
  family = binomial
)
summary(model)
```



```{r}
km_fit <- survfit(Surv(foleyday, CAUTI_LDA) ~ 1, data = cauti_new)

# ggsurvplot(km_fit, data = cauti_new, 
#            pval = TRUE, conf.int = TRUE, 
#            title = "Kaplan-Meier Survival Curve for Foley Days",
#            xlab = "Days", ylab = "Survival Probability")
```













